.de EX
.ne 5
.if n .sp 1
.if t .sp .5
.nf
.in +.5i
..
.de EE
.fi
.in -.5i
.if n .sp 1
.if t .sp .5
..
.TH LIFEKEEPER 1 "by Sebastiano Vigna" "" \" -*- nroff -*-
.SH NAME
lifekeeper \- A program that keeps your connections alive
.SH SYNOPSIS
.B lifekeeper [options]
.TP
Options:
[-h]
[-s interval]
.SH DESCRIPTION
\fBlifekeeper\fR prints an ASCII NUL character every 5 seconds. This has
no effect visually, but if someone is watching the connection for activity
it will see some. People using remote connections through firewalls might
find it useful.

.SH OPTIONS
.TP
.I "-h"
Prints some help and exits.
.TP
.I "-s interval"
The ASCII NUL will be sent every \fBinterval\fR seconds. 
.SH USAGE
The suggested way of using \fBlifekeeper\fR is to start it as a background
job in a configuration file read by your shell (e.g.,
\fI$HOME/.bash_profile\fP), storing its PID. On exit, you should kill the
process.

For instance, if you use the \fBbash\fR you should add the following lines to 
\fI$HOME/.bash_profile\fP:
.RS 2
.EX
if [ "$PS1" ]; then # Is this an interactive shell?
	lifekeeper &
	export LIFEKEEPER_PID=$! 
fi
.EE
.RE
And the following line to \fI$HOME/.bash_logout\fP:
.RS 2
.EX
kill $LIFEKEEPER_PID &>/dev/null
.EE
.RE

.SH BUGS
Please send bug reports (are you kidding? did you look at the script?) to <vigna@dsi.unimi.it>.
.SH AUTHORS
\fBlifekeeper\fR was written by Sebastiano Vigna.
